

package pascal.taie.analysis.pta.plugin.taint;

import pascal.taie.language.type.Type;

/**
 * Represents a source in taint analysis.
 */
interface Source {

    /**
     * @return type of the taint object generated by this source.
     */
    Type type();
}
